# Generated by Django 5.1.1 on 2024-11-14 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pemesanan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pemesanan',
            name='tanggalPemesanan',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='pengunjung',
            name='jenisKelamin',
            field=models.CharField(choices=[('L', 'laki-laki'), ('P', 'perempuan')], default='L', max_length=1),
        ),
    ]
