# Generated by Django 5.1.1 on 2024-11-14 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pemesanan', '0002_alter_pemesanan_tanggalpemesanan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pemesanan',
            name='tanggalPemesanan',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='pengunjung',
            name='jenisKelamin',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
