# Generated by Django 5.1.1 on 2024-11-15 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pemesanan', '0003_alter_pemesanan_tanggalpemesanan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailpemesananmenu',
            name='jumlahPesanan',
            field=models.IntegerField(default=1),
        ),
    ]
