# Generated by Django 5.1.1 on 2024-11-15 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pemesanan', '0004_detailpemesananmenu_jumlahpesanan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailpemesananmenu',
            name='totalHarga',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10),
        ),
    ]
