# Generated by Django 5.1.1 on 2024-11-15 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pemesanan', '0005_alter_detailpemesananmenu_totalharga'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pemesanan',
            name='tanggalPemesanan',
            field=models.DateField(),
        ),
    ]
