# Generated by Django 5.1.1 on 2024-11-16 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pemesanan', '0006_alter_pemesanan_tanggalpemesanan'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detailpemesananmenu',
            options={},
        ),
    ]
