# Generated by Django 5.1.1 on 2024-11-18 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pemesanan', '0007_alter_detailpemesananmenu_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pengunjung',
            name='jenisKelamin',
            field=models.CharField(choices=[('l', 'laki-laki'), ('p', 'perempuan')], max_length=11, null=True),
        ),
    ]
