# Generated by Django 5.1.1 on 2024-11-18 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pemesanan', '0008_alter_pengunjung_jeniskelamin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detailpemesananmenu',
            options={'verbose_name_plural': 'detail pemesanan menu'},
        ),
    ]
