# Generated by Django 5.1.1 on 2024-11-21 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pemesanan', '0010_alter_detailpemesananmenu_jumlahpesanan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='deskripsiMenu',
            field=models.TextField(blank=True, null=True, verbose_name='deskripsi menu'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='hargaMenu',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='harga Menu'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='namaMenu',
            field=models.CharField(default='', max_length=50, verbose_name='nama menu'),
        ),
        migrations.AlterField(
            model_name='pemesanan',
            name='tanggalPemesanan',
            field=models.DateField(verbose_name='Tanggal Pemesanan'),
        ),
        migrations.AlterField(
            model_name='pengunjung',
            name='jenisKelamin',
            field=models.CharField(choices=[('l', 'laki-laki'), ('p', 'perempuan')], max_length=11, null=True, verbose_name='jenis kelamin'),
        ),
        migrations.AlterField(
            model_name='pengunjung',
            name='namaPengunjung',
            field=models.CharField(default='', max_length=50, verbose_name='nama pengunjung'),
        ),
        migrations.AlterField(
            model_name='restoran',
            name='namaRestoran',
            field=models.CharField(default='', max_length=50, verbose_name='nama restoran'),
        ),
    ]
